apiVersion: v1
kind: Namespace
metadata:
  name: tool-gateway
---
apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: ToolGateway
metadata:
  name: tool-gateway
  namespace: tool-gateway
spec:
   env: []
#    - name: OTEL_EXPORTER_OTLP_ENDPOINT
#      value: "http://lgtm.monitoring.svc.cluster.local:4317"
#    - name: OTEL_EXPORTER_OTLP_PROTOCOL
#      value: "grpc/protobuf"
